const products = [
  {
    id: "SP_001",
    name: "tên sản phẩm 1",
    price: 100000,
    size: "S",
    quantity: 20,
    image: "/image/anh sản phẩm 1.jpg",
  },
  {
    id: "SP_002",
    name: "tên sản phẩm 2",
    price: 200000,
    size: "M",
    quantity: 10,
    image: "/image/anh sản phẩm 1.jpg",
  },
  {
    id: "SP_003",
    name: "tên sản phẩm 3",
    price: 300000,
    size: "L",
    quantity: 50,
    image: "/image/anh sản phẩm 1.jpg",
  },
  {
    id: "SP_004",
    name: "tên sản phẩm 4",
    price: 100000,
    size: "XL",
    quantity: 20,
    image: "/image/anh sản phẩm 1.jpg",
  },
  {
    id: "SP_005",
    name: "tên sản phẩm 5",
    price: 100000,
    size: "XL",
    quantity: 20,
    image: "/image/anh sản phẩm 1.jpg",
  },
  {
    id: "SP_006",
    name: "tên sản phẩm 6",
    price: 200000,
    size: "XXL",
    quantity: 20,
    image: "/image/anh sản phẩm 1.jpg",
  },
  {
    id: "SP_007",
    name: "tên sản phẩm 7",
    price: 500000,
    size: "L",
    quantity: 20,
    image: "/image/anh sản phẩm 1.jpg",
  },
  {
    id: "SP_008",
    name: "tên sản phẩm 8",
    price: 300000,
    size: "S",
    quantity: 20,
    image: "/image/anh sản phẩm 1.jpg",
  },
  {
    id: "SP_009",
    name: "tên sản phẩm 9",
    price: 400000,
    size: "XL",
    quantity: 20,
    image: "/image/anh sản phẩm 1.jpg",
  },
];
localStorage.setItem("products", JSON.stringify(products));